export enum Gender {
  male = "male",
  female = "female",
  personale = "personale",
}
export enum EmployerType {
  freelancer_hired = "freelancer hired",
  Proprietor = "Proprietor",
  administrator = "administrator",
  businessman = "businessman",
}

export enum JobSekeerType {
  freelancer = "freelancer",
  employee = "employee",
}
export enum UserType {
  employer = "employer",
  jobSekeer = "jobSekeer",
}

export enum Provider {
  facebook,
  google,
  regular,
}

export enum States {
  adrar = "adrar",
  chlef = "chlef",
  laghouat = "laghouat",
  oum_el_bouaghi = "oum el bouaghi",
  batna = "batna",
  bejaiia = "bejaiia",
  biskra = "biskra",
  bechar = "bechar",
  blida = "blida",
  bouira = "bouira",
  tamanrasset = "tamanrasset",
  tlemcen = "tlemcen",
  tiaret = "tiaret",
  tizi_ouzou = "tizi ouzou",
  Alger = "Alger",
  Djelfa = "Djelfa",
  Jijel = "Jijel",
  Setif = "Setif",
  Saiida = "Saiida",
  Skikda = "Skikda",
  Sidi_Bel_Abbes = "Sidi Bel Abbes",
  Annaba = "Annaba",
  Guelma = "Guelma",
  Constantine = "Constantine",
  Medea = "Medea",
  Mostaganem = "Mostaganem",
  Msila = "Msila",
  Mascara = "Mascara",
  Ouargla = "Ouargla",
  Oran = "Oran",
  El_Bayadh = "El Bayadh",
  Illizi = "Illizi",
  Bordj_Bou_Arreridj = "Bordj Bou Arreridj",
  Boumerdes = "Boumerdes",
  Tarf = "Tarf",
  Tindouf = "Tindouf",
  Tissemsilt = "Tissemsilt",
  El_Oued = "El Oued",
  Khenchela = "Khenchela",
  Souk_Ahras = "Souk Ahras",
  Tipaza = "Tipaza",
  Mila = "Mila",
  Aiin_Defla = "Aiin Defla",
  Naama = "Naama",
  Aiin_Temouchent = "Aiin Temouchent",
  Ghardaiia = "Ghardaiia",
  Relizane = "Relizane",
  Timimoun = "Timimoun",
  Ouled_Djellal = "Ouled Djellal",
  Beni_Abbes = "Beni Abbes",
  In_Salah = "In Salah",
  In_Guezzam = "In Guezzam",
  Touggourt = "Touggourt",
  Djanet = "Djanet",
  El_MGhair = "El MGhair",
  El_Meniaa = "El Meniaa",
}

export enum JobFileds {
  Architecture_engineering = "Architecture and engineering",
  Arts_culture_entertainment = "Arts, culture and entertainment",
  Business_management_administration = "Business, management and administration",
  Communications = "Communications",
  Community_social_services = "Community and social services",
  Education = "Education",
  Science_technology = "Science and technology",
  Installation_repair_maintenance = "Installation, repair and maintenance",
  Farming_fishing_forestry = "Farming, fishing and forestry",
  Government = "Government",
  Health_medicine = "Health and medicine",
  Law_public_policy = "Law and public policy",
  Sales = "Sales",
}

export const jobAccordingField: any = {
  "Architecture and engineering": [
    "Architect",
    "Civil engineer",
    "Landscape architect",
    "Sustainable designer",
    "Biomedical engineer",
  ],
  "Arts, culture and entertainment": [
    "Singer/songwriter",
    "Music producer",
    "Art curator",
    "Animator/video game designer",
    "Filmmaker",
    "Graphic designer",
    "Fashion designer",
    "Photographer",
  ],
  "Business, management and administration": [
    "Human resources manager",
    "Marketing assistant",
    "Accountants",
    "Secretary",
    "Entrepreneur/small business owner",
    "Real estate agent",
    "Business development manager",
  ],
  Communications: [
    "Journalist",
    "Copywriter",
    "Communications manager",
    "Public relations specialist",
    "Meeting/event planner",
    "Social media manager",
    "Brand manager",
  ],
  "Community and social services": [
    "School counselor",
    "Speech pathologist",
    "Rehabilitation counselor",
    "Licensed clinical social worker",
    "Child welfare social worker",
    "Palliative and hospice care worker",
  ],
  Education: [
    "Special education teacher",
    "School principal",
    "Superintendent",
    "College professor",
    "School librarian",
    "Substitute teacher",
  ],
  "Science and technology": [
    "Archeologis",
    "Software engineer",
    "Laboratory technician",
    "Microbiologist",
    "Physicist",
  ],
  "Installation, repair and maintenance": [
    "Auto mechanic",
    "Landscaper and groundskeeper",
    "Bicycle repairer",
    "Wind turbine technician",
    "Plumber",
  ],
  "Farming, fishing and forestry": [
    "Agricultural worker",
    "Animal breeder",
    "Nursery worker",
    "Forest and conservation worker",
    "Fisher",
  ],
  Government: [
    "School cafeteria worker",
    "Congressional staff",
    "National park ranger",
    "Mail carrier",
    "Elementary school teacher",
  ],
  "Health and medicine": [
    "Anesthesiologist",
    "Dental assistant",
    "Nurse",
    "Veterinarian",
    "Physical therapist",
  ],
  "Law and public policy": [
    "Lobbyist",
    "Public administrator",
    "Paralegal",
    "Lawyer",
    "Labor relations specialist",
  ],
  Sales: [
    "Sales associate",
    "sales development rep",
    "Account executive",
    "Regional sales manager",
    "VP of sales",
  ],
};
